import styles from './page.module.css';
import {Metadata} from "next";

export const metadata: Metadata = {
  title: 'A500 Next App',
  description: 'Generated by A500',
}

export default function Home() {
  return (
    <h1 className={styles.container}>
      {'Hello, Next'}
    </h1>
  )
}
